;
(function (w) {
    var shoppingDataSource =
        [
            {
                name: "HTC One Max",
                price: 53909,
                operatingSystem: "Android OS",
                processor: "1.7 GHz Qualcomm Snapdragon 600, Quad Core",
                resolution: "Full HD, 1920 x 1080 Pixels",
                primaryCamera: "Yes",
                size: "82.5x164.5x10.29 mm",
                weight: "217 g",
                internalMemory: "16 GB",
                image: "htc-one-max-400x400-imadqrqeyceghdba.jpeg",
                rating: 4
            },
            {
                name: "Apple iPhone 5S",
                price: 53500,
                operatingSystem: "iOS 7",
                processor: "A7 Chip with 64-bit Architecture and M7 Motion Coprocessor",
                resolution: "1136 x 640 Pixels",
                primaryCamera: "Yes, 8 Megapixel",
                size: "58.6x123.8x7.6 mm",
                weight: "112 g",
                internalMemory: "16 GB",
                image: "apple-iphone-5s-400x400-imadpppc9k3gzdjz.jpeg",
                rating: 5
            },
            {
                name: "Apple iPhone 5C",
                price: 51499,
                operatingSystem: "iOS 7",
                processor: "A6 Chip",
                resolution: "1136 x 640 Pixels",
                primaryCamera: "Yes, 8 Megapixel",
                size: "59.2x124.4x8.97 mm",
                weight: "132 g",
                internalMemory: "32 GB",
                image: "apple-iphone-5c-400x400-imadpnhzgcfgyz8e.jpeg",
                rating: 5
            },
            {
                name: "Apple iPhone 5C",
                price: 51499,
                operatingSystem: "iOS 7",
                processor: "A6 Chip",
                resolution: "1136 x 640 Pixels",
                primaryCamera: "Yes, 8 Megapixel",
                size: "59.2x124.4x8.97 mm",
                weight: "132 g",
                internalMemory: "32 GB",
                image: "apple-iphone-5c-400x400-imadpnhygtzu8s3z.jpeg",
                rating: 5
            },
            {
                name: "Apple iPhone 5C",
                price: 51499,
                operatingSystem: "iOS 7",
                processor: "A6 Chip",
                resolution: "1136 x 640 Pixels",
                primaryCamera: "Yes, 8 Megapixel",
                size: "59.2x124.4x8.97 mm",
                weight: "132 g",
                internalMemory: "32 GB",
                image: "apple-iphone-5c-400x400-imadpnhzmg3q2dt6.jpeg",
                rating: 5
            },
            {
                name: "Apple iPhone 5C",
                price: 51499,
                operatingSystem: "iOS 7",
                processor: "A6 Chip",
                resolution: "1136 x 640 Pixels",
                primaryCamera: "Yes, 8 Megapixel",
                size: "59.2x124.4x8.97 mm",
                weight: "132 g",
                internalMemory: "32 GB",
                image: "apple-iphone-5c-400x400-imadpnhyw2qnxkh5.jpeg",
                rating: 2
            },
            {
                name: "Samsung Galaxy Golden I9230",
                price: 49900,
                operatingSystem: "Android v4.2 (Jelly Bean) OS",
                processor: "1.7 GHz MSM8930 Pro, Dual Core",
                resolution: "WVGA, 480 x 800 Pixels",
                primaryCamera: "Yes, 8 Megapixel",
                size: "59.5x118x15.8 mm",
                weight: "179 g",
                internalMemory: "microSD, upto 64 GB",
                image: "samsung-galaxy-golden-i9230-400x400-imadqyvrzwnx4x7h.jpeg",
                rating: 1
            },
            {
                name: "HTC One",
                price: 48999,
                operatingSystem: "Android Jelly Bean OS",
                processor: "1.7 GHz Qualcomm Snapdragan 600, Quad Core",
                resolution: "Full HD, 1920 x 1080 Pixels",
                primaryCamera: "Yes",
                size: "68.2x137.4x9.3 mm",
                weight: "143 g",
                internalMemory: "32 GB",
                image: "htc-one-400x400-imadnzhhzyywhzzg.jpeg",
                rating: 3
            },
            {
                name: "Samsung Galaxy Note 3 N9000",
                price: 46900,
                operatingSystem: "Android v4.3 (Jelly Bean) OS",
                processor: "1.9 GHz Quad + 1.3 GHz Quad",
                resolution: "Full HD, 1920 x 1080 Pixels",
                primaryCamera: "Yes, 13 Megapixel",
                size: "79.2x151.2x8.3 mm",
                weight: "168 g",
                internalMemory: "32 GB",
                image: "samsung-galaxy-note-3-n9000-400x400-imadq4ypdrhrynxh.jpeg",
                rating: 4
            },
            {
                name: "Samsung Galaxy Note 3 N9000",
                price: 46900,
                operatingSystem: "Android v4.3 (Jelly Bean) OS",
                processor: "1.9 GHz Quad + 1.3 GHz Quad",
                resolution: "Full HD, 1920 x 1080 Pixels",
                primaryCamera: "Yes, 13 Megapixel",
                size: "79.2x151.2x8.3 mm",
                weight: "168 g",
                internalMemory: "32 GB",
                image: "samsung-galaxy-note-3-galaxy-note-3-n9000-400x400-imadzrek9qwryxyn.jpeg",
                rating: 5
            },
            {
                name: "Nokia Lumia 1020",
                price: 45999,
                operatingSystem: "Windows Phone 8 OS",
                processor: "1.5 GHz Qualcomm Snapdragon S4, Dual Core",
                resolution: "WXGA, 1280 x 768 Pixels",
                primaryCamera: "Yes, 41 Megapixel",
                size: "71.4x130.4x10.4 mm",
                weight: "158 g",
                internalMemory: "32 GB",
                image: "nokia-lumia-lumia-1020-400x400-imadzkgsyttbgt3f.jpeg",
                rating: 3
            },
            {
                name: "Nokia Lumia 1020",
                price: 45999,
                operatingSystem: "Windows Phone 8 OS",
                processor: "1.5 GHz Qualcomm Snapdragon S4, Dual Core",
                resolution: "WXGA, 1280 x 768 Pixels",
                primaryCamera: "Yes, 41 Megapixel",
                size: "71.4x130.4x10.4 mm",
                weight: "158 g",
                internalMemory: "32 GB",
                image: "nokia-lumia-lumia-1020-400x400-imadzkgshuhjwfmk.jpeg",
                rating: 3
            },
            {
                name: "Nokia Lumia 1020",
                price: 45999,
                operatingSystem: "Windows Phone 8 OS",
                processor: "1.5 GHz Qualcomm Snapdragon S4, Dual Core",
                resolution: "WXGA, 1280 x 768 Pixels",
                primaryCamera: "Yes, 41 Megapixel",
                size: "71.4x130.4x10.4 mm",
                weight: "158 g",
                internalMemory: "32 GB",
                image: "nokia-lumia-lumia-1020-400x400-imadzkgsskuq6tt4.jpeg",
                rating: 3
            },
            {
                name: "Sony Xperia Z Ultra",
                price: 44990,
                operatingSystem: "Android v4.2 (Jelly Bean) OS",
                processor: "2.2 GHz Qualcomm Snapdragon 800, Quad Core",
                resolution: "Full HD, 1920 x 1080 Pixels",
                primaryCamera: "8 MP Primary Camera with Auto Focus",
                size: "92.2x179.4x6.5 mm",
                weight: "212 g",
                internalMemory: "16 GB",
                image: "sony-xperia-z-ultra-400x400-imadzbkyx4mvceyn.jpeg",
                rating: 4
            },
            {
                name: "BlackBerry Q10",
                price: 44000,
                operatingSystem: "BlackBerry 10",
                processor: "1.5 GHz, Dual Core",
                resolution: "720 x 720 Pixels",
                primaryCamera: "8 Megapixel",
                size: "66.8x119.6x10.35 mm",
                weight: "139 g",
                internalMemory: "16 GB",
                image: "blackberry-q10-400x400-imadhkzz5qtfhzy5.jpeg",
                rating: 3
            },
            {
                name: "LG G2",
                price: 43490,
                operatingSystem: "Android v4.2.2 (Jelly Bean)",
                processor: "2.26 GHz Qualcomm Snapdragon 800, Quad Core",
                resolution: "Full HD, 1920 x 1080 Pixels",
                primaryCamera: "13 Megapixel",
                size: "70.9x138.5x8.9 mm",
                weight: "143 g",
                internalMemory: "32 GB",
                image: "lg-g2-32-gb-400x400-imadzzebyf2fccjx.jpeg",
                rating: 5
            },
            {
                name: "Samsung Galaxy S4 I9500",
                price: 40690,
                operatingSystem: "Android v4.2.2 (Jelly Bean)",
                processor: "1.6 GHz Quad + 1.2 GHz Quad",
                resolution: "Full HD, 1920 x 1080 Pixels",
                primaryCamera: "13 Megapixel",
                size: "69.8x136.6x7.9 mm",
                weight: "130 g",
                internalMemory: "16 GB",
                image: "samsung-galaxy-s4-i9500-400x400-imadkbmd6quvhc9t.jpeg",
                rating: 5
            },
            {
                name: "LG Optimus G E975",
                price: 28499,
                operatingSystem: "Android v4.1 (Jelly Bean)",
                processor: "1.5 GHz Qualcomm Snapdragon S4 Pro, Quad Core",
                resolution: "WXGA, 1280 x 768 Pixels",
                primaryCamera: "13 Megapixel",
                size: "68.9x131.9x8.45 mm",
                weight: "145 g",
                internalMemory: "32 GB (25 GB User Memory)",
                image: "lg-optimus-g-e975-400x400-imadjfuysxeaeu5y.jpeg",
                rating: 4
            }
        ];
    w["ShoppingDataSource"] = shoppingDataSource;
})(window);